### ISSUE TITLE
Hybrid authentication doesn't work

### ISSUE THREAD

**Issue by JiriChara** [intridea/omniauth-github#54]
Does `omniauth-github` support hybrid authentication workflow like for example `omniauth-facebook`? I have a fully independent front-end application which handles authentication/authorization/friendly forwarding and all that stuff. What I would like to to is to `window.open` `http://jch-dev.com:3000/auth/github/callback?code=83062c75a657f7f2d6e8` with `redirect_uri` set and `client_id set`. Basically something like this:

```javascript
var data = {
  client_id: 'my-client-id',
  redirect_uri: 'http://jch-dev.com:3000/auth/github/callback'
};
window.open('//github.com/login/oauth/authorize?' + $.param(data));
```

This works well and it also redirects back to the server with the `code`, but then something goes wrong:

```
Started GET "/auth/github/callback?code=785cdb4262dcaef8b010" for 127.0.0.1 at 2015-08-26 14:33:08 +0200
I, [2015-08-26T14:33:08.139086 #2128]  INFO -- omniauth: (github) Callback phase initiated.
E, [2015-08-26T14:33:09.624436 #2128] ERROR -- omniauth: (github) Authentication failure! invalid_credentials: OAuth2::Error, : 
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

OAuth2::Error (: 
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}):
  oauth2 (1.0.0) lib/oauth2/client.rb:113:in `request'
  oauth2 (1.0.0) lib/oauth2/access_token.rb:107:in `request'
```

Regular (non-client side) authentication works like a charm. So if I point browser to `/auth/github` I get the JSON response back from my omniauth-callbacks controller. Can someone please help me?

**Comment by JiriChara** [comment]
I am sorry for firing this bug it was my mistake. I forgot to request `user:email` scope and that's why the user was not found in the omni-callbacks controller.. :tired_face:
